---
title: "shiny_dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
  runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(shiny)
library(plotly)
library(tidyverse)





set.seed(1)

instacart = read_csv("./data/instacart_train_data.csv.zip") %>%
  clean_names()

```



Column {.sidebar}
-----------------------------------------------------------------------

```{r}
department = instacart %>% distinct(department) %>% pull()

# selectInput widget
selectInput("department_choice", label = h3("Select department"),
            choices = department, selected = "produce")

max_id = instacart %>% distinct(order_id) %>% max()
min_id = instacart %>% distinct(order_id) %>% min()

# sliderInput widget
sliderInput("order_id_range", label = h3("Choose order id range"), min = min_id, 
        max = max_id, value = c(1, 1000000))

renderPrint({ 
  input$department_choice
})
```


Row
-----------------------------------------------------------------------

### Chart A

```{r}
renderPlotly({
    instacart %>%
    filter(department == input$department_choice,
           order_id %in% input$order_id_range[1]:input$order_id_range[2]) %>%
    

    plot_ly(x = ~order_dow, y = ~order_hour_of_day, type = "scatter", mode = "markers",
          alpha = 0.02)
})
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Chart B

```{r}
renderPlotly({
  instacart %>% 
  count(department) %>% 
  mutate(department = fct_reorder(department, n)) %>% 
  plot_ly(x = ~department, y = ~n, color = ~department, type = "bar")
})
```

### Chart C

```{r}
renderPlotly({
  instacart %>%
  mutate(departnemt = fct_reorder(department, order_hour_of_day)) %>%
  plot_ly(x = ~department, y = ~order_hour_of_day, color = ~department, type = "box")

})


```

